### ISSUE TITLE
Markdown Monster shuts down when trying to create a new file

### ISSUE THREAD

**Issue by icemanind** [RickStrahl/MarkdownMonster#1010]
When I open Markdown Monster and click to create a new document or try to open a document, I get an error that says "The Editor WebView Control has failed and the application has to shut down. Please restart Markdown Monster.". I attached a screenshot of the error.

![image](https://user-images.githubusercontent.com/401480/221901780-b3021a6d-9776-40e9-aa47-982334d2bfd4.png)

I have tried reinstalling both Markdown Monster and WebView2. Nothing seems to resolve it. I am using version 2.8.6,  but this issue also occurred on version 2.8.5. I am running Windows 11 Pro, version 22H2, currently all up to date, as of 2/28/2023. 

Device Specifications:

Device name	LPT049-22
Full device name	LPT049-22.lh.com
Processor	11th Gen Intel(R) Core(TM) i5-11500H @ 2.90GHz   2.92 GHz
Installed RAM	32.0 GB (31.7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Windows Specifications:
Edition	Windows 11 Pro
Version	22H2
Installed on	‎12/‎6/‎2022
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by icemanind** [comment]
I am not running the portable version. I installed it using Chocolatey:

`choco install markdownmonster`

It's how I've always installed Markdown Monster. I did try to delete the `Temp_WebView_Environment` folder, but that did not solve the issue. Also, I tried running `mmcli cleanup-webview`, but it got an error:

![image](https://user-images.githubusercontent.com/401480/222261331-8a524c51-d861-41b1-9782-d4a75632de44.png)

Any other suggestions?

**Comment by RickStrahl** [comment]
Does the `Temp_WebView_Environment` folder get recreated after you delete it and restart?

How are you starting MM? Opening to an empty environment and you fail when you add a new document? Or starting from Command Line?

Honestly, I'm not sure what the problem could be. The failure is in the WebView crashing - typically that's related to some issue with the WebView environment either being corrupted or not being able to write to the output location. 

Are you running your configuration out of the default folder, or have you changed the configuration/common folder?

Can you check your error log - is there anything in there at the bottom that relates to the WebView? I don't see anything in the online logs.

One other thing to try is turn off Hardware Accelleration in the settings. If you can launch go to settings and type in `Hardware` into the search box then check **Disable Hardware Accelleration**. Shut down and restart. 

ps. the bug for the cleanup is fixed in the update, but all it does is essentially remove the folder so you already went through that.

**Comment by icemanind** [comment]
Yes, the `Temp_WebView_Environment` folder does get recreated after I delete it and restart it. I start MM by just going to the shortcut in my start menu. I did not try opening from the command line..

The configuration is out of the box. It was working prior to version 2.8.5. At the same time though, I also had installed Citrix Workspace, which also uses the WebView component. So i don't know if upgrading caused the issue or if Citrix somehow screwed things up. I did uninstall Citrix and still have the same issue though. I also tried re-installing WebView. I was hoping you had some knowledge of like a secret log or something that could help me narrow down the cause more.

Thanks!

**Comment by RickStrahl** [comment]
Did you try the Disable Hardware Acceleration setting? This may especially be pertinent running in a VPC environment.

If you install an older version (pre-2.85), does that work?

You can find older installs here:

https://github.com/RickStrahl/MarkdownMonsterReleases/tree/master/v2/v2.8

I'm also curious if this would be affecting other WebView based applications. For example: https://websurge.west-wind.com/, which also uses the WebView (for previews).

Sorry, I know this is a hassle, but I'm more or less grasping at straws here...

Ultimately it sounds like a corrupt WebView configuration or install, but a reinstall should fix that. MM installs and uses the latest version of the Runtimes and SDK bits, so it couldn't be new features clobbering behavior. It could be a problem if an old version gets installed (by the Citrix installer?) but then a reinstall should update the runtime.

I log all this stuff, but unfortunately WebView crashes are not captured reliably, and they provide no system information  on why it crashed. I don't see even see any of your crashes in my telemetry logs.

FWIW, I haven't heard any other reports of this sort of problem although there's an occasional mention of crashed WebView errors, but typically they are not repeatable but one off.

**Comment by icemanind** [comment]
I did try disabling hardware acceleration. Still no luck. I also uninstalled Markdown Monster and installed version 2.84, which also did not work. I know for a fact that 2.84 used to work just fine without any issues. So I am leaning towards this not being an issue with Markdown Monster and more of an issue with WebView. Installing Citrix must have broke something in WebView and even though I am reinstalling WebView, it must not be doing a clean install or something.

Anyway, thanks for your help with this. If you can think of anything else to try, I am all ears.

**Comment by RickStrahl** [comment]
You can uninstall the Microsoft WebView Runtime from the Apps and Programs in Windows, which should in theory clear out everything. I think what can happen in an update install is that it won't fully uninstall if something is using the WebView, but the explicit uninstaller would detect and probably display error info for that and not uninstall.

Once completely uninstalled like that you can try reinstalling with MM which should do a clean install at that point. 

This is the first I've heard of a corrupt WebView install (apparently).

**Comment by RickStrahl** [comment]
Can you give v2.8.8.4 another try from [here](https://markdownmonster.west-wind.com/download).

I've made  a slight tweak to the way the editor initializes the WebView - it's possible that this has an impact in your situation.

Also as mentioned it'd be worthwhile trying to run another application that uses a WebView like [West Wind WebSurge](https://websurge.west-wind.com). 

There are a few other suggestions for WebView running applications in this Twitter thread I started:

https://twitter.com/RickStrahl/status/1633991126725300225?s=20

**Comment by icemanind** [comment]
Hi Rick!

I got it working! I first tried the version you linked above and that didn't fix it. Then I installed WebSurge, as you suggested. WebSurge didn't work either, but WebSurge at least told me what the issue was!! Apparently Symantec Endpoint Protection (my antivirus software) was blocking WebView2 from running. After uninstalling Symantec Endpoint Protection, I tried Markdown Monster again and it fired right up and I was able to create a new document without any issues at all now!

Thanks so much for helping me through this! You went above and beyond helping me, especially considering the issue wasn't even a bug in Markdown Monster. So thanks for that!

Alan

**Comment by RickStrahl** [comment]
That's great to hear.

Can you tell me what was different with the error when it occurred in WebSurge that pointed you at the AV software?

I think WebSurge doesn't explicitly capture the `WebViewUnresponsive` event, so it fails hard eventually, but I have to look. Let me know what was different though, that will be good to know.

+++ Rick ---

**Comment by icemanind** [comment]
Hi Rick. I wish I had taken a screenshot, but I didn't. But basically, it showed a white screen and it said "Norton Protection is blocking this from rendering". Something to that effect. I can see if I can install it on a virtual machine and duplicate it so I can snag a screen shot for you.
