### ISSUE TITLE
Publish broken

### ISSUE THREAD

**Issue by Mehul** [RickStrahl/MarkdownMonster#184]
Hi Rick, not sure which build did it but the publishing has broke for me. Well, it will publish once, then display an error message:

![image](https://cloud.githubusercontent.com/assets/174004/25101260/64a64644-2368-11e7-9258-18ed41c3ff4b.png)

I've attached the error log too.

[MarkdownMonsterErrors.txt](https://github.com/RickStrahl/MarkdownMonster/files/926464/MarkdownMonsterErrors.txt)

So in order to update a post, I need to quit Mdm and post again but it shows the error every time. 

Does the error log help?

**Comment by RickStrahl** [comment]
Thanks for the log - that helps.

Does the post make it to your site if you check it explicitly? 

Looking at the log it looks like the error occurs when trying to display the URL that is returned from the post API (a ShellExecute() call basically). 

I've fixed this by wrapping the code in a catch and logging handler - let's see what comes back from that:

2469e306b8f5451cf53941e9049cb1c9119ecab0

It's checked in if you want to build yourself.

Otherwise, the quick fix for you might be:

* Open up the Weblog Configuration Tab
* Set an explicit PreviewUrl

This will force using the Preview URL instead of the value returned for the post from the server.

FWIW, I can't duplicate the error here, so it's likely related to how the server is returning the post information. It might be useful to check out the Fiddler trace on posts that fail to see what the server is returning for Post.link and/or Post.url.

**Comment by RickStrahl** [comment]
I've updated [the download](https://markdownmonster.west-wind.com/download.aspx) with the fix - it's updated on the site, but not on Chocolatey until the next build drops.

**Comment by Mehul** [comment]
Thanks @RickStrahl, that may have fixed it. It's posting now.

Still seeing this in the error log:

4/17/2017 3:18:33 PM - Failed to display Weblog Url after posting: 

I saw your quick fix idea but I don't see a way to set PreviewURL. My config looks like this one:
https://markdownmonster.west-wind.com/docs/images/CreateEditWebLog.png

**Comment by RickStrahl** [comment]
Yeah that's what I suspected. The URL is completely blank (otherwise it would show up in the new error/log  message), but I'm not sure how that's possible.

The logic is this basically this:

                if (!string.IsNullOrEmpty(weblogInfo.PreviewUrl))
                {
                    var url = weblogInfo.PreviewUrl.Replace("{0}", WeblogModel.ActivePost.PostId.ToString());
                    ShellUtils.GoUrl(url);
                }
                else
                {
                    if (!string.IsNullOrEmpty(postUrl))
                        ShellUtils.GoUrl(postUrl);
                    else
                        ShellUtils.GoUrl(new Uri(weblogInfo.ApiUrl).GetLeftPart(UriPartial.Authority));
                }

Can you see how this would break with the values you have for your publishing target?

It looks like the ApiUrl isn't set in your case.  Not sure why or how that's failing exactly, without looking at what you have in the fields. You can click the configuration icon (downarrow) on the publishing toolbar icon then go to configuration and see **exactly** what's set in the configuration (including the PreviewUrl which I removed because it really shouldn't be necessary if the blog is properly responding with a URL).

**Comment by Mehul** [comment]
Ah, that's where you set the PreviewURL, thanks, that fixed it. No error in the log now. 

APIUrl was set but not PreviewURL.

**Comment by RickStrahl** [comment]
Well normally the preview URL shouldn't need to be set. The way this is supposed to work is that a post is sent to the server and then MM pulls the new post and receives the Post.link/url and uses that to display the actual post. PreviewURL should only be necessary if for some reason the server doesn't return the post url (as my custom blog used to :smile:). 

I've seen other errors in this space, so I'm curious what exact path through is causing this error to occur based on the code in my last message. Any chance you can share your JSON record (domain/url if sensitive). Curious how this would break. The API Url should always be set and so work to retrieve the base URL.

**Comment by Mehul** [comment]
Hey Rick, what's a good/simple way to capture that JSON info for you? I tried Web Surge but got this error:
![image](https://cloud.githubusercontent.com/assets/174004/25292164/da45cffe-2689-11e7-8d15-d26813e409f3.png)

**Comment by RickStrahl** [comment]
Best thing is probably Fiddler to monitor what goes out over the wire.

WebSurge capture should work too, but you have to add the certificate configuration (button on the top right). 

![image](https://cloud.githubusercontent.com/assets/1374013/25300236/254191e6-26d0-11e7-91bf-89ddee0b94fb.png)

**Comment by RickStrahl** [comment]
Any more info on this?

**Comment by Mehul** [comment]
I'll email you.

**Comment by RickStrahl** [comment]
Hmmm... yeah I see the problem. The link returned from the blog engine is a partial URL, 

```
<member>
            <name>link</name>
            <value>
              <string>/blogs/aspnet/archive/2017/04/24/test-post-4-24.aspx</string>
            </value>
          </member>
```
which will fail if you try to navigate to it. The link is supposed to return a full URL not a relative url.

 There's really no way around this, but the most recent fixes should at least keep from crashing as I've wrapped that code into try/catch block. You just won't see anything from happening.

**Comment by Mehul** [comment]
Ok, thanks.

**Comment by RickStrahl** [comment]
Thanks for following up on that to verify. Is this code still crashing for you? 1.3 should not no longer crash as the above code has been in there since we first started this thread.

**Comment by Mehul** [comment]
No, that PreviewURL seems to fix it, thanks. I'll see if I can get our admin to take a look about the url situation. Keep this ticket open a couple of days please. Thanks.

**Comment by RickStrahl** [comment]
Will do.

**Comment by Mehul** [comment]
Btw, it's still has the issue where I'll publish, change something in the post, republish, but it won't update the site. I'll email you the logs where I started MM, published (site update), then republished a couple of times where the site wasn't updated. I'll email the logs2.zip, thanks.

**Comment by RickStrahl** [comment]
Can you tell based on the logging if the subsequent post is sending to the server? I don't see this behavior in any of the different providers I publish to - for example on my blog I very frequently repost and have no problem with the updates.

IOW, are you sure there's not something on the server that's preventing the update? 

What provider are you using? MetaWeblog API? And connecting to what? A custom implementation?

**Comment by Mehul** [comment]
Yes, MetaWeblog and its been heavily customized.

Not sure if it is sending. But the behavior is odd. Let me record a video so you can see what I mean.

**Comment by Mehul** [comment]
@RickStrahl Good news, our admin fixed it so it returns the absoluteURL. It's working great now, thanks for helping with this!
