### ISSUE TITLE
Cannot download dictionary files anymore

### ISSUE THREAD

**Issue by umern** [RickStrahl/MarkdownMonster#675]
Attempting to change Dictionary to en-GB but it just shows 'downloading' in the status bar indefinitely.
Using the latest version MM v1.23.14
Thanks

**Comment by RickStrahl** [comment]
It's already been fixed in 2c8008c7.

Latest pre-release download has the update.

**Comment by umern** [comment]
Hi @RickStrahl 

Thanks for the prompt update.

I downloaded and installed 1.23.14.2 and it still stuck at 'Downloading License..

![image](https://user-images.githubusercontent.com/11923910/87768287-ce578f00-c813-11ea-80fc-1f3f9f994f0e.png)

Been going around 5 mins now..

**Comment by RickStrahl** [comment]
Give it another shot with `12.23.14.3`. Apparently the `.2` version hadn't this update in it.

**Comment by umern** [comment]
Hi @RickStrahl 

Have you updated the download link at https://markdownmonster.west-wind.com/download.aspx - I selected https://west-wind.com/files/MarkdownMonsterSetup_Latest.exe - but that is still showing 12.23.14.2 in the install dialog and About dialog?

And the dictionary download still does not complete...

Thanks
