### ISSUE TITLE
The Editor WebView Control has failed and the Application has to shut down

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#838]
When pasting (Ctrl+V) an Image from the Clipboard into a Markdown File in the Editor the system is crashing over and over again when saving the Picture into a different folder than the document's folder. 
When pasting into the same directory as the current file, things are ok. 
When saving the picture first to disk and using the Image-Insertion-Dialogue from the Menu, things are ok as well. 
So - I can work - but it is annoying. 
Kind regards
Rene

I am running an updated Windows 10 PC.

**Comment by RickStrahl** [comment]
Hmmm... I can't duplicate this. Can you give me steps for this? What type of image? Can you try with say the Markdown Monster image from the MM homepage from the browser just to be sure there's not some issue with the image source?  Here's what I'm doing:

* Open browser 
* Copy image from browser (MM main image in this case)
* Switch to open document in MM
* Ctrl-V
* On dialog save to c:\temp\ (different folder than document)

This works for me without a problem.

There are two things I can think of that can go wrong here:

* Image source - where did the clipboard image come from?
* File issues - permissions, invalid name etc.

Now even if either of these happen there should be error dialogs that pop up rather than hard carshes. I think the hard crashes are due to some of the recent async conversions and the error handling falling through in an async task. I'll double check for that.

But main issue is to try and figure out why the image save is failing in the first place.

The error log (Help->Show Error Log) might also have more info.

**Comment by conradakunga** [comment]
Getting the same issue

![image](https://user-images.githubusercontent.com/1281845/128667635-b21d5611-ac40-4353-9cde-0ea1c364fdd4.png)

MM v 2.0.8 on Windows Microsoft Windows Version 21H1 (OS Build 19043.1110)

This issue is sporadic - generally pasting and saving works OK. This error occurs sometimes, and I'm not sure what the pattern is.

I've been using this flow for as long as I have been using MM. It is definitely not a permissions issue.  The source is captured screenshots using SnagIt.

**Comment by realB12** [comment]
Hi Rick: 
When copying an image in my Browser by right-clicking the image and choosing copy (your way) : all fine. 
However: when using the latest version of Greenshot Scrapping-Tool (https://getgreenshot.org/) I am getting the same Shutdown Notice as Conrad mentioned above when doing the same with SnagIt. 
![image](https://user-images.githubusercontent.com/3463881/128708874-9e211e78-26af-4456-8a62-a1ebda5b6bc6.png)
The errof log shows the following: 
"09.08.2021 14:56:25 - Snippets::AddIn::OnWindowLoaded Error: Der angeforderte Wert "2D" konnte nicht gefunden werden.
"  - in english: The requested value "2D" was not found. 
Currently I do not have a clue where this "2D" value is coming from (most probably from the GreenShot Tool). 

Most probably you might be right with the file-format.  What file format should it be then? (I can change the output format in the GreenShot tool).

**Comment by realB12** [comment]
Hi Rick, 
I have changed now the Output format of my Snipping Tool from *.png to *.jpg. 
It seems that this works now. 
The funny thing is, that within MM the *.jpg file is converted back to *.png ???

**Comment by realB12** [comment]
b.t.w. This issue has occurred with the last or second-last update. Before all this has been stable and no issue on my side.

**Comment by RickStrahl** [comment]
So checked code and sue enough there was one place where code was not properly using async semantics to interact with the document. I've made those changes. There's also been an update to the WebView control which might address some of the `RenderProcessUnresponsive` errors that I've seen in relation to this.

**Comment by RickStrahl** [comment]
Pasting doesn't preserve the image format - only the raw image. How the file is saved is based on the extension you provide. The default if no extension is .png, but if you provide a filename with .jpg that will be created.

As mentioned there were some left over issues in the paste code that didn't respect full async processing which might have accounted for the errors.

LAtest version has those issues fixed plus uses a newer version of the WebView control from Microsoft (the unstability is something that was reported and they supposedly worked on). So give 2.0.8.4 or later a try and see if that fixes the issues.

**Comment by RickStrahl** [comment]
Image formats are very tricky to detect and to properly save the document. Based on the error though it doesn't look like the problem is the image capture itself. 

If you could verify:

* Is the image saved where you tell it to and does the image show correctly in an image viewer?

The error we're seeing here is the Editor control's host WebView blowing up, which seems to suggest the problem is related to inserting the image **link** (not the image) and this was the code that was updated as I mentioned above.

So before anymore discussion, please do me a favor and try 2.0.8.4 or later to see if that addresses the issue. 

FWIW, I've seen this error once even when trying for quite a while to duplicate it with varying types of images. Also I use SnagIt for all of my image captures (not the addin but just raw SnagIt, then copy and paste into MM) and I don't have issues with that. Not sure about greenshoot I should check that out to see if there are some image format issues there, but that would show up as a broken image or a conversion error on the image import not with a Editor WebView crash.

**Comment by bladewolf55** [comment]
Version 2.0.8.4 doesn't fix my file saving error.

**Comment by RickStrahl** [comment]
@bladewolf55 Another update with 2.0.9 with additional updates to the async preview updates.

I can't duplicate this error with your steps from the other issue any longer. I was able to very intermittently with 2.0.3 but since then I've not been able to get it to fail. 

I have an issue in with the WebView team to see if we can get more error information.  Your stack trace is great - I guess you have explicit Dr. Watson debugging enabled in Windows to forec the debugger dialog? I can't remember how to enable that - it would be useful if I can get it to fail again. Unfortunately your stack trace only points to code in the WebView, and not any source from the MM end so nothing I can do with that unfortunately :frowning:

**Comment by bladewolf55** [comment]
To be honest, I just have a default VS installation so I don't know what I
have enabled differently. Maybe I installed WinDbg or something similar at
some point.

I'll try 2.0.9 and let you know. Thanks, Rick, I know this is a pesky one.

**Comment by bladewolf55** [comment]
Sorry, same problem in 2.0.9.

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{4D00C0D1-9434-4EB6-8078-8697A560334F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
  Source=mscorlib
  StackTrace:
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Wpf.WebView2.Uninitialize(Boolean browserCrashed)
   at Microsoft.Web.WebView2.Wpf.WebView2.Dispose(Boolean disposing)
   at System.Windows.Interop.HwndHost.Finalize()
```

**Comment by RickStrahl** [comment]
@bladewolf55 I think that error happens **after** the WebView is already on its shutdown - I bet that error is normally swallowed if no debugger is present. The problem is something that happens before this that triggers the error that makes the WebView unresponsive and then has to shut down.

Another question - are you by chance running Edge Canary versions rather than having installed the WebView2 runtime? The canary builds will override installed runtimes, and perhaps there's something different there causing the control to crash (old version perhaps)?

The related issue in the WebView2 Repo is here:

https://github.com/MicrosoftEdge/WebView2Feedback/issues/1630

**Comment by bladewolf55** [comment]
I created a virtual machine with a clean Windows 10 Pro install, and installed MM. The error still occurs. It's not the file name length, but instead how long I wait before clicking Save after entering a file name.

## Repro
1.  Open MM
2. Ctrl+N
3. "asdf"
4. Ctrl+S
5. Wait 20 seconds
6. Click Save

The reason I experienced it with a long file name is, of course, how long it took to type in the name.

**Comment by realB12** [comment]
Have installed 2.0.9 and can confirm the "timeout" issue. It's not the length of the name nor the path. It's just the fact that long names and changing paths take longer save.  
Good to know that "hurry up" is a workaround that works for me.

**Comment by RickStrahl** [comment]
Thanks guys - I can now duplicate.

Not sure what to make of this., but I think what's happening is that something is locking the UI thread and I think it's the Save dialog that pops up. I suspect it has to do with the async wrapping. Taking a look and experimenting.

**Comment by RickStrahl** [comment]
Ok... so I've pinned this down to the  Save File Dialog that I'm using. Apparently what's happening is that this control does something to the UI event loop if the dialog is open for a long time, that the WebView doesn't like and it's causing the UI thread on the WebView to die or corrupt.

After some experimentation it looks like calling the dialog invocation inside of a Dispatcher call seems to fix the issue. With this code in place the problem disappears for me now:

```cs
 await mmApp.Model.Window.Dispatcher.InvokeAsync(() => { result = sd.ShowDialog(); },DispatcherPriority.ApplicationIdle);
```

I've updated the code in 2.0.9.2. Give that a try

---

### More detailed info for reference.

The problem appears to be that the dialog is called inside of an Async call context. Without the `Dispatcher.InvokeAsync()` wrapper in the code below the error does not occur when:

* The dialog is open less than 20 seconds
* No async code is fired before the call

For the last item this means if I Save As with no document text the error does not occur. But as soon as either of those `await` calls are made then the dialog fails. The actual failure occurs then at the next async call into the WebBrowser control:

```cs
// method handler is async
SaveAsCommand = new CommandBase(async (parameter, e) =>
{
   bool isEncrypted = parameter != null && parameter.ToString() == "Secure";

   var tab = Model.Window.TabControl?.SelectedItem as TabItem;

   var editor = tab?.Tag as MarkdownDocumentEditor;
   if (editor == null)
       return;

   // preset folder: Current doc (if open), Last Used Folder, folder browser Path
   var filename = editor.MarkdownDocument.Filename;
   var folder = Path.GetDirectoryName(editor.MarkdownDocument.Filename);
   if (string.IsNullOrEmpty(folder) || !Directory.Exists(folder))
   {
       folder = mmApp.Configuration.LastFolder;
       if (string.IsNullOrEmpty(folder) || !Directory.Exists(folder))
           folder = Model.Window?.FolderBrowser?.FolderPath;
       if (string.IsNullOrEmpty(folder) || !Directory.Exists(folder))
           folder = KnownFolders.GetPath(KnownFolder.Libraries);
   }


   if (filename == "untitled")
   {
      // this `await` call is what is the trigger for the dialog failure
       var match = Regex.Match(await editor.GetMarkdown(), @"^# (\ *)(?<Header>.+)", RegexOptions.Multiline);

       if (match.Success)
       {
           filename = match.Groups["Header"].Value;
           if (!string.IsNullOrEmpty(filename))
               filename = FileUtils.SafeFilename(filename);
       }
   }

   var sd = new SaveFileDialog
   {
       FilterIndex = 1,
       InitialDirectory = folder,
       FileName = filename,
       CheckFileExists = false,
       OverwritePrompt = true,
       CheckPathExists = true,
       RestoreDirectory = true
   };

   var mdcryptExt = string.Empty;
   if (isEncrypted)
       mdcryptExt = "Secure Markdown files (*.mdcrypt)|*.mdcrypt|";

   sd.Filter =
       $"{mdcryptExt}Markdown files (*.md)|*.md|Markdown files (*.markdown)|*.markdown|All files (*.*)|*.*";

   bool? result = null;
   try
   {
      // Without the Dispatcher call we fail after 20 seconds - with it doesn't
       await mmApp.Model.Window.Dispatcher.InvokeAsync(() => { result = sd.ShowDialog(); },DispatcherPriority.ApplicationIdle);
   }
   catch (Exception ex)
   {
       mmApp.Log("Unable to save file: " + editor.MarkdownDocument.Filename, ex);
       MessageBox.Show(
           $@"Unable to open file:\r\n\r\n" + ex.Message,
           "An error occurred trying to open a file",
           MessageBoxButton.OK,
           MessageBoxImage.Error);
   }

   if (!isEncrypted)
       editor.MarkdownDocument.Password = null;
   else
   {
       var pwdDialog = new FilePasswordDialog(editor.MarkdownDocument, false) {Owner = Model.Window};
       bool? pwdResult = pwdDialog.ShowDialog();
   }

   if (result != null && result.Value)
   {
       try
       {
           editor.MarkdownDocument.Filename = sd.FileName;
           if (!await editor.SaveDocument())
           {
               MessageBox.Show(Model.Window,
                   $"{sd.FileName}\r\n\r\nThis document can't be saved in this location. The file is either locked or you don't have permissions to save it. Please choose another location to save the file.",
                   "Unable to save Document", MessageBoxButton.OK, MessageBoxImage.Warning);
               SaveAsCommand.Execute(tab);
               return;
           }

           Model.Configuration.LastFolder = Path.GetDirectoryName(sd.FileName);
       }
       catch (Exception ex)
       {
           mmApp.Log($"Failed to save file: {sd.FileName}", ex, false, LogLevels.Warning);

           MessageBox.Show(Model.Window,
               $"{sd.FileName}\r\n\r\nThis document failed to save in this location:\r\n\r\n{ex.Message}",
               "Unable to save Document",
               MessageBoxButton.OK, MessageBoxImage.Warning);
           return;
       }
   }

   Model.Window.SetWindowTitle();

   // failure happens as part of this call which touches both editor and preview WebViews
   await Model.Window.PreviewMarkdownAsync(editor, keepScrollPosition: true);
}, (s, e) => { return Model.IsEditorActive; });
}
```

**Comment by realB12** [comment]
with 2.0.9.2 Problem persists
"Fast" save works. 20 Seconds Dealy is crashing. 
with the following error: 
12.08.2021 11:29:00 - Editor WebView Control Process Failed: RenderProcessUnresponsive Unresponsive

**Comment by RickStrahl** [comment]
@realB12  Hmmm... I can't make it fail anymore no matter how long I wait now where it was failing after 20 seconds.

Can anybody else in this thread confirm what they're seeing?

This would be specific to the Save operation - either Ctrl-s on a new file or Save As with an existing file.

There may still be other places in the application where the same sort of Save File Dialog logic is used (like image saving etc.).

**Comment by bladewolf55** [comment]
Version 2.0.9.2 is working for me. Thank, Rick. Challenging!

**Comment by RickStrahl** [comment]
@realB12 can you try this again in 2.0.8.10. 

I ended up still seeing a failure if I waited long enough. I've tried another combination of code using `InvokeAsync()` instead and that seems to now work for various `ShowDialog()` operatoins (the other frequent failure was image pasting and saving).

```cs
var sd = new SaveFileDialog
{
    Filter = "Image files (*.png;*.jpg;*.gif;)|*.png;*.jpg;*.jpeg;*.gif|All Files (*.*)|*.*",
    FilterIndex = 1,
    Title = "Save Image from Clipboard as",
    InitialDirectory = initialFolder,
    CheckFileExists = false,
    OverwritePrompt = true,
    CheckPathExists = true,
    RestoreDirectory = true,
    ValidateNames = true,
};

// await InvokeAsync() seems to fix
var result2 = await mmApp.Model.Window.Dispatcher.InvokeAsync(() => sd.ShowDialog());

if (result2 == null || !result2.Value)
    return null;
```

**Comment by realB12** [comment]
Hi Rick, 
I am not compiling from the sourcecode. 
So which .exe file do I have to download and install for the 2.0.8.10 version? Is https://github.com/RickStrahl/MarkdownMonsterReleases/commits/master/v1.28/MarkdownMonsterSetup-1.28.exe the correct one?

**Comment by realB12** [comment]
Hi Rick, 
Have installed above mentioned 1.28 Version. The Timeout problem does no longer occur on my machine with this older version. 
for your info: Before changing to 1.28 I did some tests with the newest version again - and it crashed even after updating Windows 10 and rebooting.

**Comment by realB12** [comment]
Hi Rick, 
Have installed the 2.0.9.5 version now. The problem seems to be solved!!

**Comment by RickStrahl** [comment]
Thanks @realB12. 

The specific issue with `Save As` seems to be resolved but now hunting down some other instances of that have similar modal dialog failures. I think I got them all but please keep your eyes peeled for any other `The Editor WebView Control has failed` errors and please report them if they should pop up.

Thanks all for your help on tracking this tricky bug down.

Blog post details some of the issues and workarounds we've uncovered here:

[WebView and Modal Dialogs in WPF Async Code](https://weblog.west-wind.com/posts/2021/Aug/16/WebView-and-Modal-Dialogs-in-WPF-Async-Code)
