### ISSUE TITLE
MM starts with a black window

### ISSUE THREAD

**Issue by cwattengard** [RickStrahl/MarkdownMonster#94]
Scenario:
Lenovo P50 with 4k display, external monitor with 1080p display.
External monitor is primary display.

Starting application it just displays a black rectangle. It still "works" though. I can see the mouse cursor change between the caret and the pointer when hovering over different places in the rectangle.

Dragging the window from the external monitor to the laptop monitor fixes it. If I put it halfway, the part remaining on the external monitor is still black, while the part on the laptop screen is working correctly. Dragging it back to the external monitor from the laptop screen also works. It does not go back to black.

Making it start on the laptop screen, either by setting it as the primary screen, or by dragging it there and quitting, makes it start as normal. No black rectangle.

OS: Windows 10.0.14393
.NET: 4.0.30319 (I think. It's the highest version folder in C:\Windows\Microsoft.NET\Framework\)

**Comment by punker76** [comment]
@cwattengard Can you test this scenario with the main demo ([.zip](https://github.com/MahApps/MahApps.Metro/releases/download/1.4.0/MetroDemo.zip)) from the [1.4.0 MahApps release](https://github.com/MahApps/MahApps.Metro/releases/tag/1.4.0)? Thx

**Comment by cwattengard** [comment]
The app in the ReleaseNET40 folder does not start at all... The one in the ReleaseNET45 folder works fine.

**Comment by RickStrahl** [comment]
@punker76  I think the problem is on my end. I'm rendering the window offscreen because all the tabs are opening and jumping about so I just move the window offscreen, and pull it back in. I think there might be a timing bug or potentially some sort of failure in the InvokeAsync() code. 

I made a change to the Dispatcher.InvokeAsync() code to fire in the background and now I can't make it fail anymore. Then again I switched the code back and it **still** doesn't want to fail so maybe it is something else. But by the looks of it definitely appears that the window is offscreen somewhere where it's not accessible. You can move and maximize.

Anyway, I've just pushed up 1.1.2.1 - see if that works any better for you @cwattengard.

FWIW, I also checked TeamViewer which also wasn't working previously and that appears to be working now as well.

**Comment by cwattengard** [comment]
Still same issue.

**Comment by RickStrahl** [comment]
Can you give another try with 1.1.5. I added some additional code to refresh the window rendering after a short delay.

**Comment by cwattengard** [comment]
Sorry. The issue is still there.
It comes to life when it resizes due to the dpi difference between the two screens, as seen here: https://drive.google.com/file/d/0B3W3f2ElrYbocnl6SFJNdUktRlU/view?usp=sharing

**Comment by RickStrahl** [comment]
Oh wow, that's something completely different. That's definitely not something that's happening from within MM that's some weird OS interaction. It looks like the window shows then blacks out and loses all rendering. In the previous update I added another explicit Invalidation round to force a re-rerender, but that's clearly not doing anything here. If anything the form renders, then clears which is just bizarre.

Not sure what to do with this and I definitely can't duplicate that with any similar setup (hooked to a TV, and a 4k monitor running 1080p res. If anybody else can repo please share HW and SW setup so we can compare notes to see what combo is causing this craziness.

**Comment by RickStrahl** [comment]
Can you give another try with 1.1.10. I switched to .NET 4.6.1 in this release which has a ton of WPF related tweaks and improvements espcially related to DPI and render issues. It's possible that this may be addressed as part of that.

**Comment by RickStrahl** [comment]
Another day and another update. We've updated to use .NET 4.6.2 (if available). Again many improvements in the WPF rendering pipeline in the base .NET framework that might address this issue.

**Comment by cwattengard** [comment]
New release new issue... Now it does not display on the 1080p screen at all... It starts in HUGE-mode, then resizes and goes black. It's fine if I move it to the laptop screen, but actually goes black again when it redraws on the 1080p screen.

**Comment by RickStrahl** [comment]
Sigh. What video driver? Are you using recent drivers?

**Comment by cwattengard** [comment]
It's a lenovo P50 with Nvidia Quadro M2000M using the latest drivers (376.33).
A Samsung 2494hs screen is connected via DVI (DP->DVI), this is the 1080p screen. The Lenovo has a 4k panel.

**Comment by cwattengard** [comment]
In an interesting turn of events. Fullscreen (F11) chrome now also goes black. The only thing left is the "Press F11 to exit full screen" and the status bar.

**Comment by RickStrahl** [comment]
You mean when you run Chrome you see some similar behavior? It certainly sounds like a possible video driver issue perhaps some odd interaction with that particular screen. 

Sorry I don't know what else to suggest at this point. I haven't heard of anybody else running into this sort of thing.

**Comment by RickStrahl** [comment]
Any change with recent updates or any more info?

I'm going to close this issue, since we're at an impasse here with no way to reproduce and also no other reports of the same error occurring. I wish had other ideas but I'm not sure what would cause this behavior.

**Comment by RickStrahl** [comment]
Can you try v1.1.28 and set this Configuration key:

```json
  "DisableHardwareAcceleration": true
```

This disables GPU rendering and we've found that in least one other case that seems to fix the black screen rendering issue. Since MM doesn't do any fancy screen UI this has minimal effect on performance.

**Comment by cwattengard** [comment]
Setting "DisableHardwareAcceleration" to true fixes the issue.

**Comment by RickStrahl** [comment]
Great. Thanks for checking Christian.
